# Generated by Django 4.0.4 on 2022-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_images_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_model',
            name='image',
            field=models.FileField(default='a', upload_to=''),
        ),
    ]
