# Generated by Django 4.0.4 on 2022-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_images_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_model',
            name='image',
            field=models.ImageField(default='a', upload_to=''),
        ),
    ]
