# Generated by Django 4.0.4 on 2022-04-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_images_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_model',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
